# Change the service name and container name, hostname to your project name
# Change the volumes to your project path
services:
  japanese-llm-study:
    container_name: japanese-llm-study
    build:
      context: .
      args:
        - USER_NAME=${USER_NAME}
      dockerfile: dockerfile
    image: n622jwith/japanese-llm-study:latest
    environment:
      - DISPLAY=${DISPLAY}
      - "QT_X11_NO_MITSHM=1"
    volumes:
      # GUI
      - /tmp/.X11-unix:/tmp/.X11-unix
      - $HOME/.Xauthority/:/home/${USER_NAME}/.Xauthority:ro
      # ssh key
      - $HOME/.ssh:/home/${USER_NAME}/.ssh:ro
      # workspace
      - $HOME/ML/japanese-llm-study/:/home/${USER_NAME}/japanese-llm-study
      - $HOME/ML/dataset/:/home/${USER_NAME}/dataset
    hostname: japanese-llm-study
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
    tty: true
    user: "${UID}:${GID}"
